name: Daily multi-chain scan
on:
  schedule:
    - cron: '0 9 * * *' # daily at 09:00 UTC
  workflow_dispatch: {}

jobs:
  run:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Use Node.js 20
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install deps
        run: npm ci

      - name: Run scan (one-shot)
        env:
          BASE_RPC: ${{ secrets.BASE_RPC }}
          OP_RPC: ${{ secrets.OP_RPC }}
          ARBITRUM_RPC: ${{ secrets.ARBITRUM_RPC }}
          REWARD_CONTRACTS: ${{ secrets.REWARD_CONTRACTS }}
          SCAN_BLOCK_WINDOW: ${{ secrets.SCAN_BLOCK_WINDOW }}
          SCAN_WEBHOOK_URL: ${{ secrets.SCAN_WEBHOOK_URL }}
        run: |
          mkdir -p reports
          npm run scan:once

      - name: Upload report artifact
        uses: actions/upload-artifact@v4
        with:
          name: scan-report
          path: reports/*.json
